In [4]:
import numpy as np
a=np.array([5,5,5])
a

array([5, 5, 5])

In [5]:
type(a)

numpy.ndarray

In [6]:
len(a)

3

In [7]:
a[0:]

array([5, 5, 5])

In [10]:
c=np.zeros(2)
c

array([0., 0.])

In [13]:
d=np.ones(3)
d

array([1., 1., 1.])

In [14]:
e=np.empty(3)
e

array([1., 1., 1.])

In [15]:
f=np.arange(9)
f

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
g=np.arange(2,20,2)
g

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
h= np.linspace(0, 10, num=5)
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
i= np.linspace(0, 100, num=200)
i

array([  0.        ,   0.50251256,   1.00502513,   1.50753769,
         2.01005025,   2.51256281,   3.01507538,   3.51758794,
         4.0201005 ,   4.52261307,   5.02512563,   5.52763819,
         6.03015075,   6.53266332,   7.03517588,   7.53768844,
         8.04020101,   8.54271357,   9.04522613,   9.54773869,
        10.05025126,  10.55276382,  11.05527638,  11.55778894,
        12.06030151,  12.56281407,  13.06532663,  13.5678392 ,
        14.07035176,  14.57286432,  15.07537688,  15.57788945,
        16.08040201,  16.58291457,  17.08542714,  17.5879397 ,
        18.09045226,  18.59296482,  19.09547739,  19.59798995,
        20.10050251,  20.60301508,  21.10552764,  21.6080402 ,
        22.11055276,  22.61306533,  23.11557789,  23.61809045,
        24.12060302,  24.62311558,  25.12562814,  25.6281407 ,
        26.13065327,  26.63316583,  27.13567839,  27.63819095,
        28.14070352,  28.64321608,  29.14572864,  29.64824121,
        30.15075377,  30.65326633,  31.15577889,  31.65

In [22]:
j= np.ones(5, dtype=np.int8)
j

array([1, 1, 1, 1, 1], dtype=int8)

In [23]:
k=np.ones(5, dtype=np.float64)
k

array([1., 1., 1., 1., 1.])

In [24]:
l= np.arange(2, 20)
l

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [25]:
m = np.arange(5, 51, 5)
m

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

# Array Functions

## if there is one float value in array, entire array's data type will become float

In [26]:

a = np.array([64, 99,63,74,5,2.1])
a

array([64. , 99. , 63. , 74. ,  5. ,  2.1])

## Sort function

In [28]:
a.sort()
a

array([ 2.1,  5. , 63. , 64. , 74. , 99. ])

In [29]:
b = np.array([84, 79,69,23,66,1.1])
b

array([84. , 79. , 69. , 23. , 66. ,  1.1])

## concatenate

In [35]:
c =np.concatenate((a, b))
c


array([ 2.1,  5. , 63. , 64. , 74. , 99. , 84. , 79. , 69. , 23. , 66. ,
        1.1])

In [33]:
c.sort()
c


array([ 1.1,  2.1,  5. , 23. , 63. , 64. , 66. , 69. , 74. , 79. , 84. ,
       99. ])