In [3]:
#list of lists
import numpy as np
b=np.array([[5,5,5,], [5,5,5], [5,5,5]])
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [4]:
type(b)

numpy.ndarray

In [5]:
len(b)

3

In [6]:
b[0]

array([5, 5, 5])

In [7]:
b[0:]

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [9]:
c= np.ones((3,4))
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
d=np.ones((3,4), dtype=np.int8)
d

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [12]:
e= np.zeros((5,4))
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
f=np.empty((4,5))
f

array([[6.26475239e-321, 2.12199579e-314, 4.94065646e-324,
        2.33419537e-312, 1.39067116e-309],
       [8.69381679e-311, 2.13684976e-311, 1.69760311e-313,
        1.55367112e+030, 3.72620332e-212],
       [8.89660644e-312, 8.89689864e-312, 8.89689864e-312,
        5.01402526e+180, 1.71703293e+088],
       [4.85178805e+021, 1.36617664e+161, 2.13507542e+257,
        7.27180102e+228, 9.64813213e-315]])

# Array Function

## concatenate

In [17]:
a = np.array([[1, 2], [5, 4]])
a

array([[1, 2],
       [5, 4]])

In [21]:
b = np.array([[6, 9], [4, 8]])
b

array([[6, 9],
       [4, 8]])

In [22]:
np.concatenate((a, b))

array([[1, 2],
       [5, 4],
       [6, 9],
       [4, 8]])

In [23]:
np.concatenate((a, b), axis = 0)

array([[1, 2],
       [5, 4],
       [6, 9],
       [4, 8]])

In [24]:
np.concatenate((a, b), axis=1)

array([[1, 2, 6, 9],
       [5, 4, 4, 8]])

In [25]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [33]:
a.reshape(3,2,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

## Converting 1d array into 2 d array

In [36]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a.shape

(9,)

In [39]:
# row wise
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [40]:
b.shape

(1, 9)

In [44]:
# column wise
d = a[ :, np.newaxis]
d

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [45]:
d.shape

(9, 1)